# lypning-mp frozen shim: unicodedata — NFC/NFD over ONE bounded repertoire, and a
# loud refusal for everything else. See micropython/lib/README.md.
#
# The repertoire is the 161 precomposed letters of Latin-1 Supplement + Latin
# Extended-A (U+00C0..U+017F) and the 13 combining marks they decompose to.
# That is what the corpus asks for: every observed import of this module
# compares text that differs only by the composition of a West/North European
# name — Dalén, Åkesson, Öberg — where composed é and decomposed e + U+0301
# must compare equal.
#
# CPython's UCD is hundreds of KB and the whole binary must fit 700,000 B, so
# what is not carried is REFUSED, never passed through as if normalisation had
# succeeded:
#
#   _R  every code point in Unicode 14.0 that NFC/NFD would touch and this
#       file cannot handle — canonical decompositions, non-zero combining
#       classes, second elements of composition pairs, Hangul syllables and
#       jamo — as 409 ranges. Any of them exits 90.
#   _G  every (starter, one of our marks) pair that composes in full Unicode
#       to a character outside the repertoire (K + U+0301 -> U+1E30, and 356
#       more). Attempting one exits 90.
#
# A character with no canonical decomposition, no combining class and no
# composition is unaffected by NFC/NFD — all of ASCII, all of CJK, most of the
# BMP — so passing it through is the identity CPython computes, not an
# approximation. Compatibility decompositions do not affect NFC/NFD either, so
# U+FF21, U+0149 and U+017F are correctly left alone; NFKC/NFKD themselves are
# refused by name. So are category/name/lookup/decimal/digit/numeric/
# combining/east_asian_width/bidirectional/mirrored/decomposition — a guessed
# category table is exactly the silently-wrong answer this contract exists to
# prevent.
#
# The tables were generated by running CPython 3.11.15's unicodedata over every
# code point (decomposition/combining/normalize), never hand-typed, and then
# diffed straight back against it: every one of the 1,112,064 code points on
# its own, every character below U+2000 followed by each of the 13 marks, every
# base with two marks, randomised strings, both forms, both directions,
# idempotence and the cross-form identities. 2,492,872 comparisons, 87,890
# refusals, 0 divergences -- and the same diff over the built binary rather
# than this source, because a shim that agrees with CPython under CPython
# proves nothing about MicroPython.

unidata_version = "14.0.0"  # the UCD the tables were generated from

# The 13 marks, and their canonical combining class as a RANK ("1" < "2"),
# which is all the ordering algorithm compares. 202 = attached below, 230 =
# above.
_M = ("\u0300\u0301\u0302\u0303\u0304\u0306\u0307\u0308\u030a\u030b"
      "\u030c\u0327\u0328")
_CC = "2222222222211"

# Canonical decomposition of U+00C0..U+017F, two chars per code point: the
# ASCII base letter and the mark index as chr(0x30 + i). "  " = no canonical
# decomposition (x, /, Ø, Đ, Ł, Œ, ŋ, ĸ, ı and the compatibility-only ones).
# Read forwards for NFD, searched at an even offset for NFC.
_D = (
    "A0A1A2A3A7A8  C;E0E1E2E7I0I1I2I7  N3O0O1O2O3O7    U0U1U2U7Y1    a0a1a2a3"
    "a7a8  c;e0e1e2e7i0i1i2i7  n3o0o1o2o3o7    u0u1u2u7y1  y7A4a4A5a5A<a<C1c1"
    "C2c2C6c6C:c:D:d:    E4e4E5e5E6e6E<e<E:e:G2g2G5g5G6g6G;g;H2h2    I3i3I4i4"
    "I5i5I<i<I6      J2j2K;k;  L1l1L;l;L:l:        N1n1N;n;N:n:      O4o4O5o5"
    "O9o9    R1r1R;r;R:r:S1s1S2s2S;s;S:s:T;t;T:t:    U3u3U4u4U5u5U8u8U9u9U<u<"
    "W2w2Y2y2Y7Z1z1Z6z6Z:z:  "
)

# Varint alphabet: 5 payload bits, +32 means "another char follows".
_A = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz#$"

# Refused code points, as (gap-from-previous-range, length-1) varint pairs.
_R = (
    "WD1D1SF152A312Z1216Dn60303P2b11V4090651012P6P441h11103042A0V0M1103042N1B"
    "4v11D32125252B21t4i110111110e2A74a1KG0l2010G026252113Z10UQW5890O3181214h"
    "12y17g1N1Sf10702070G03337y2010C2904110U0q102050G0B220z20G0k301090228141s"
    "10f10B390a30B04071b30301041111071a3110B390o3040A013u22D3i32D3i21R0101090"
    "90404040C07510132411B090404040801010C0$20708011o20o3$7zA2qT1U0z40A0h60l4"
    "2x61d20K720m1D1Ft101010101030X1150102111c18s11w10B1Z20u421C16406031c6v61"
    "04v26L252b125271010101U2q11610231D251I221721k6C403Br1031k31I0U2q104020N0"
    "10Q0202010M010A42121612121Y13m1363x11nz10oG2j40W3VgH5S010101010101010101"
    "010102010106111111111M04130D010101010101010101010102010106111111111M0233"
    "0mhT049W11m21q80b10t40RHv12b10$20C0l7012215110q10s70IZzAyg8j820102910102"
    "13Z22f3Z22AC1410111118nMFjU0Y70r44oq1010e1240b51zH3ZC1v4An13W60f10E0Q010"
    "E0D1b22a106131#10i2090g31o51m2110C290E634j6030N0n209431h70A131#30s31p30j"
    "81r70704140y40p20I0n20bD0Y8011n20ugJ4x16vb11ibJ0$b5B358726U3D5X42xj361G2"
    "61114b86tB0z13Wl16j36rrZ2zG"
)

# Dangerous starters, one varint-delta list per mark of _M, "|"-separated: the
# pair composes in full Unicode but the result is outside the repertoire.
_G = (
    "k292L92l1Q8A868A861F1v11p21E1XF422664842266411g23T3es6171717171717171717"
    "17187171s2$1|d24237G4237n1Q311355134631135513461F1v11R1t11E1XF4226648422"
    "664117X27P7cs617171717171717171717187171s2$1|w2W1cn71N1J1|b2H3CH3f28AE8A"
    "E1z41E1|d2IEIh22F1682F16k71x1171YB8CC8Cp2BLBpl61Z11|eH1eB8CC8Ch2512BD512"
    "Bzo61|X212225111211311812225111211311X7151UZd71|e2F1GC31z2W1r31kHCKCDq1A"
    "51116544235111654429Y41F1|t32|ZX1W1|X2611246C6111146d3W1x5x6|a213S13|l2W"
    "1"
)

_S = None  # range starts / ends / danger set, decoded on first normalize()
_E = None
_GS = None


def _unsupported(what):
    raise NotImplementedError("lypning: unsupported: " + what)


def _refuse(what):
    _unsupported("argument: unicodedata.normalize(" + what + ")")


def _u(cp):
    return "U+%04X" % cp


def _nums(t):
    out = []
    n = sh = 0
    for c in t:
        v = _A.index(c)
        n |= (v & 31) << sh
        if v < 32:
            out.append(n)
            n = sh = 0
        else:
            sh += 5
    return out


def _load():
    global _S, _E, _GS
    _S = []
    _E = []
    cp = 0
    ns = _nums(_R)
    for i in range(0, len(ns), 2):
        cp += ns[i]
        _S.append(cp)
        cp += ns[i + 1]
        _E.append(cp)
        cp += 1
    _GS = set()
    for mi, part in enumerate(_G.split("|")):
        b = 0
        for d in _nums(part):
            b += d
            _GS.add(b * 16 + mi)


def _risky(cp):
    lo = 0
    hi = len(_S)
    while lo < hi:
        mid = (lo + hi) // 2
        if cp < _S[mid]:
            hi = mid
        else:
            lo = mid + 1
    return lo > 0 and cp <= _E[lo - 1]


def _cc(ch):
    i = _M.find(ch)
    return _CC[i] if i >= 0 else "0"


def _pair(b, mi):
    """The composite of base char b and mark index mi, or None."""
    k = b + chr(0x30 + mi)
    i = _D.find(k)
    while i >= 0:
        if not i % 2:
            return chr(0xC0 + i // 2)
        i = _D.find(k, i + 1)
    return None


def _order(buf):
    """Canonical ordering: a stable sort of each non-starter run by class."""
    sw = 0
    for i in range(1, len(buf)):
        c = _cc(buf[i])
        if c == "0":
            continue
        j = i
        while j and _cc(buf[j - 1]) > c:
            buf[j], buf[j - 1] = buf[j - 1], buf[j]
            j -= 1
            sw += 1
    return sw


def _compose(buf):
    res = []
    nc = 0
    st = -1  # index in res of the starter a mark may attach to
    lc = "0"  # class of the last character appended after that starter
    for ch in buf:
        c = _cc(ch)
        if st >= 0 and lc < c:  # not blocked from res[st]
            b = res[st]
            mi = _M.find(ch)
            k = _pair(b, mi)
            if k:
                res[st] = k
                nc += 1
                continue
            if ord(b) * 16 + mi in _GS:
                _refuse(_u(ord(b)) + "+" + _u(ord(ch)))
        if c == "0":
            st = len(res)
            lc = "0"
        else:
            lc = c
        res.append(ch)
    return res, nc


def _flush(buf, nd, pm, nfc, force):
    """Normalise one chunk. Returns (text, input length); text is None when the
    chunk came out byte-identical to its input and the caller can still skip
    building a result string at all."""
    same = True
    if nd or pm:
        sw = _order(buf)
        if nfc:
            # Every one of the nd composites split into exactly one base and
            # one mark, so if nothing was reordered, no mark came from the
            # input, and nd compositions happened, each one went back together.
            buf, nc = _compose(buf)
            same = not sw and not pm and nc == nd
        else:
            same = not sw and not nd
    if same and not force:
        return None, len(buf)
    return "".join(buf), len(buf)


def normalize(form, s):
    if form in ("NFKC", "NFKD"):
        _refuse(form)
    if form not in ("NFC", "NFD"):
        raise ValueError("invalid normalization form")
    # Nothing below U+00C0 has a canonical decomposition, a combining class or
    # a composition, so such a string is already its own NFC and NFD.
    if not s or max(s) < "\xc0":
        return s
    if _S is None:
        _load()
    nfc = form == "NFC"
    res = []  # finished chunks, once there is anything to finish
    buf = []  # the decomposed chunk being built
    nd = pm = 0  # composites split in it; marks it took from the input
    pre = 0  # leading characters of s known to pass through untouched
    chg = False
    # The input is normalised a chunk at a time because a list of 100,000
    # one-character strings exhausts MicroPython's heap, and heap exhaustion in
    # the middle of a file is not a subset boundary anyone can act on. A chunk
    # may end before any STARTER without changing the answer: no non-starter
    # run is split, and the only backwards composition across the seam would be
    # starter + starter, which is Hangul and already refused by _R. While every
    # chunk so far is unchanged nothing is materialised at all, so the ordinary
    # case in the corpus -- NFC over a file that is already NFC -- allocates no
    # output and returns s itself.
    for ch in s:
        cp = ord(ch)
        if 0xC0 <= cp < 0x180:
            i = (cp - 0xC0) * 2
            if _D[i] != " ":
                if len(buf) > 2048:
                    txt, n = _flush(buf, nd, pm, nfc, chg)
                    if txt is None:
                        pre += n
                    else:
                        if not chg:
                            res.append(s[:pre])
                            chg = True
                        res.append(txt)
                    buf = []
                    nd = pm = 0
                buf.append(_D[i])
                buf.append(_M[ord(_D[i + 1]) - 0x30])
                nd += 1
                continue
        elif cp >= _S[0] and _risky(cp):
            _refuse(_u(cp))
        elif cp > 0x2FF and _M.find(ch) >= 0:
            buf.append(ch)
            pm += 1
            continue
        if len(buf) > 2048:
            txt, n = _flush(buf, nd, pm, nfc, chg)
            if txt is None:
                pre += n
            else:
                if not chg:
                    res.append(s[:pre])
                    chg = True
                res.append(txt)
            buf = []
            nd = pm = 0
        buf.append(ch)
    txt, n = _flush(buf, nd, pm, nfc, chg)
    if txt is None and not chg:
        return s
    if not chg:
        res.append(s[:pre])
    res.append(txt)
    return "".join(res)


def is_normalized(form, s):
    return normalize(form, s) == s


def _stub(name):
    def f(*a):
        _unsupported("attribute: unicodedata." + name)

    return f


bidirectional = _stub("bidirectional")
category = _stub("category")
combining = _stub("combining")
decimal = _stub("decimal")
decomposition = _stub("decomposition")
digit = _stub("digit")
east_asian_width = _stub("east_asian_width")
lookup = _stub("lookup")
mirrored = _stub("mirrored")
name = _stub("name")
numeric = _stub("numeric")
