"""Ask Cerebras what this key can see, through the one door. Prints no key.

A 403 is either "this key is rejected" or "this key cannot have that model", and
the two have different owners: one is a secret to rotate, the other an
entitlement to request. `harvesting/preflight.py` refuses a model substitution,
so knowing which is the whole question.

The key is `.strip()`ed in `pipeline.synth_generate.backend_from_env` for the
same reason the generator needs it: a secret stored with a trailing newline
yields an Authorization header the API rejects with 403, which is
indistinguishable from a revoked key unless you look for it. Needs
`PYTHONPATH=training`.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request

from pipeline.backends import USER_AGENT, BackendError
from pipeline.synth_generate import CEREBRAS_BASE_URL, MODEL, backend_from_env


def main() -> int:
    raw = os.environ.get("CEREBRAS_API_KEY", "")
    key = raw.strip()
    backend = backend_from_env()
    if backend is None:
        print("CEREBRAS_API_KEY is not set in this job", file=sys.stderr)
        return 2
    # Shape only, never the value: length, prefix, and whether it arrived with
    # surrounding whitespace, which is the failure this exists to report.
    print("key: %d chars (%d before strip), prefix %r, stripped_whitespace=%s"
          % (len(key), len(raw), key[:4], raw != key))

    # The listing is DIAGNOSTIC, never the gate, because it answers a different
    # question than the one the job is about to spend on: a key can be entitled
    # to inference without being entitled to enumerate. It stays advisory even
    # though both now succeed -- the 403s of 2026-09-18 were this client failing
    # to name itself, not the key, and a gate that cannot tell those apart is
    # what stopped four dispatches before either question was asked.
    listing = None
    # Same User-Agent as every other call this tree makes. Without it the edge
    # answers 403 before the key is checked, which is the failure this probe
    # exists to tell apart from a rejected key -- and did not, until 2026-09-19.
    req = urllib.request.Request(CEREBRAS_BASE_URL + "/models",
                                 headers={"Authorization": "Bearer " + key,
                                          "User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            listing = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        print("GET /models: HTTP %d -- cannot enumerate with this key; "
              "the completion below is what decides." % exc.code)
    except (urllib.error.URLError, OSError, ValueError) as exc:
        print("GET /models: %s -- cannot enumerate; the completion below decides."
              % type(exc).__name__)

    if listing is not None:
        ids = sorted(str(m.get("id", "")) for m in (listing.get("data") or []) if isinstance(m, dict))
        print("models visible to this key (%d):" % len(ids))
        for i in ids:
            print("  %s%s" % (i, "   <-- the pinned one" if i == MODEL else ""))
        if MODEL not in ids:
            print("\n%s is NOT visible. harvesting/preflight.py refuses a substitution "
                  "and so does this: a bank generated by a different model is a "
                  "different bank." % MODEL, file=sys.stderr)
            return 1

    # THE GATE. A visible model can still be unentitled, and an invisible one can
    # still complete, so this is the only check whose answer is the question the
    # job is about to spend on. `reasoning_effort="none"` is required, not tidy:
    # with reasoning on, this model answers in a separate channel and leaves
    # `content` empty, so the call succeeds and returns nothing.
    try:
        out = backend.complete([{"role": "user", "content": "Reply with the single word: ready"}],
                               max_tokens=64, temperature=0.0, reasoning_effort="none")
    except BackendError as exc:
        # The message may quote the response body; the status is what matters.
        print("chat/completions failed: %s" % str(exc).split(":")[0], file=sys.stderr)
        return 1
    reply = out.text.strip()
    print("completion content: %r" % reply[:60])
    if not reply:
        print("the call succeeded and returned no content: the reasoning "
              "contract is wrong, not the key", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
