"""Ask Cerebras what this key can see. Prints status and model ids, never a key.

A 403 on the first completion is either "this key is not valid" or "this key
cannot have that model", and the two have different owners: one is a secret to
rotate, the other is an account entitlement. `harvesting/preflight.py` refuses a
model substitution, so knowing which is the whole question.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request

WANTED = "qwen-3.8-27b"


def main() -> int:
    key = os.environ.get("CEREBRAS_API_KEY", "")
    if not key:
        print("CEREBRAS_API_KEY is not set in this job", file=sys.stderr)
        return 2
    print("key present: %d characters, prefix %r" % (len(key), key[:3]))
    req = urllib.request.Request(
        "https://api.cerebras.ai/v1/models",
        headers={"Authorization": "Bearer " + key})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as exc:
        # The body can echo the request; print the status and nothing else.
        print("GET /v1/models -> HTTP %d" % exc.code, file=sys.stderr)
        print("401/403 here means the key itself is rejected, so this is a "
              "secret to rotate rather than an entitlement to request.",
              file=sys.stderr)
        return 1
    except Exception as exc:                                     # noqa: BLE001
        print("GET /v1/models failed: %s" % type(exc).__name__, file=sys.stderr)
        return 1
    ids = sorted(e.get("id", "") for e in data.get("data", []))
    print("models visible to this key (%d):" % len(ids))
    for i in ids:
        print("  %s%s" % (i, "   <-- the pinned one" if i == WANTED else ""))
    if WANTED not in ids:
        print("\n%s is NOT visible to this key. harvesting/preflight.py refuses a "
              "substitution, and so does this: a bank generated by a different "
              "model is a different bank." % WANTED, file=sys.stderr)
        return 1
    print("\n%s is available; a 403 on completions is then a per-endpoint or "
          "quota restriction rather than a missing model." % WANTED)
    return 0


if __name__ == "__main__":
    sys.exit(main())
