"""Ask Cerebras what this key can see, through the official SDK. Prints no key.

A 403 is either "this key is rejected" or "this key cannot have that model", and
the two have different owners: one is a secret to rotate, the other an
entitlement to request. `harvesting/preflight.py` refuses a model substitution,
so knowing which is the whole question.

The key is `.strip()`ed here for the same reason the generator does it: a secret
stored with a trailing newline yields an Authorization header the API rejects
with 403, which is indistinguishable from a revoked key unless you look for it.
"""
from __future__ import annotations

import os
import sys

WANTED = "qwen-3.8-27b"


def main() -> int:
    raw = os.environ.get("CEREBRAS_API_KEY", "")
    key = raw.strip()
    if not key:
        print("CEREBRAS_API_KEY is not set in this job", file=sys.stderr)
        return 2
    # Shape only, never the value: length, prefix, and whether it arrived with
    # surrounding whitespace, which is the failure this exists to report.
    print("key: %d chars (%d before strip), prefix %r, stripped_whitespace=%s"
          % (len(key), len(raw), key[:4], raw != key))

    from cerebras.cloud.sdk import Cerebras

    client = Cerebras(api_key=key)
    try:
        listing = client.models.list()
    except Exception as exc:                                     # noqa: BLE001
        code = getattr(exc, "status_code", None)
        print("models.list() failed: %s%s"
              % (type(exc).__name__, (" HTTP %d" % code) if code else ""), file=sys.stderr)
        if code in (401, 403):
            print("401/403 on the listing means the key itself is rejected: rotate "
                  "the CEREBRAS_API_KEY secret. It is not a model entitlement.",
                  file=sys.stderr)
        return 1
    ids = sorted(getattr(m, "id", "") for m in (getattr(listing, "data", None) or []))
    print("models visible to this key (%d):" % len(ids))
    for i in ids:
        print("  %s%s" % (i, "   <-- the pinned one" if i == WANTED else ""))
    if WANTED not in ids:
        print("\n%s is NOT visible. harvesting/preflight.py refuses a substitution "
              "and so does this: a bank generated by a different model is a "
              "different bank." % WANTED, file=sys.stderr)
        return 1

    # One real completion, because a visible model can still be unentitled.
    try:
        out = client.chat.completions.create(
            messages=[{"role": "user", "content": "Reply with the single word: ready"}],
            model=WANTED, max_completion_tokens=16)
    except Exception as exc:                                     # noqa: BLE001
        code = getattr(exc, "status_code", None)
        print("chat.completions failed: %s%s"
              % (type(exc).__name__, (" HTTP %d" % code) if code else ""), file=sys.stderr)
        return 1
    reply = (out.choices[0].message.content or "").strip()
    print("completion ok: %r" % reply[:40])
    return 0


if __name__ == "__main__":
    sys.exit(main())
