"""Render the battery as the brief every generator agent is handed.

The brief carries everything a program needs to be *runnable* — the exact stdin
bytes, the argv, the files that will exist in the working directory — and
nothing that would let a generator work backwards to the answer. The expected
stdout lives only in ``tasks.jsonl`` and is never shown.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harness as H  # noqa: E402

OUT = H.STUDY / "task-brief.md"


def main() -> int:
    tasks = H.load_tasks()
    lines = ["<!-- GENERATED by study/gen_taskbrief.py. Do not edit. -->",
             "# The tasks", "",
             "%d tasks. Each program is passed to the interpreter as `-c PROGRAM`, "
             "so it must be complete on its own: no shell, no argparse, no functions "
             "left uncalled." % len(tasks), ""]
    for i, t in enumerate(tasks, 1):
        lines.append("## %d. `%s`" % (i, t["id"]))
        lines.append("")
        lines.append(t["ask"])
        lines.append("")
        if t.get("stdin") is not None:
            lines.append("* stdin is exactly these bytes: `%s`" % t["stdin"].encode("unicode_escape").decode())
        else:
            lines.append("* stdin is empty")
        if t.get("argv"):
            lines.append("* the arguments after the program are: %s"
                         % ", ".join("`%s`" % a for a in t["argv"]))
        if t.get("files"):
            for name, content in t["files"].items():
                lines.append("* the working directory contains `%s`:" % name)
                lines.append("")
                lines.append("  ```")
                for ln in content.splitlines() or [""]:
                    lines.append("  " + ln)
                lines.append("  ```")
        lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%d bytes, %d tasks)" % (OUT.relative_to(H.ROOT), OUT.stat().st_size, len(tasks)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
