"""Generate the capability brief from the engine's own tables.

A hand-written list of what the subset supports is a list that goes stale on the
next commit, and a treatment prompt that lies about the engine measures the lie
rather than the prompt. So the brief is *extracted* — from ``builtins.rs``,
``methods.rs``, ``modules.rs`` and ``route.rs`` — and regenerating it is one
command. If a table moves, this script fails loudly rather than emitting a
shorter brief.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUST = ROOT / "src" / "lypning" / "assets" / "rust" / "src"
OUT = ROOT / "study" / "prompts" / "capability-brief.md"


def table(path: Path, name: str) -> list:
    text = (RUST / path).read_text(encoding="utf-8")
    m = re.search(r"const %s: &\[&str\] = &\[(.*?)\];" % re.escape(name), text, re.S)
    if not m:
        raise SystemExit("table %s not found in %s — the engine moved; fix this script"
                         % (name, path))
    return re.findall(r'"([^"]+)"', m.group(1))


def fmt(names) -> str:
    return ", ".join("`%s`" % n for n in names)


def main() -> int:
    builtins = table(Path("builtins.rs"), "BUILTINS")
    modules = table(Path("modules.rs"), "MODULES")
    mp_modules = table(Path("route.rs"), "MICROPYTHON_MODULES")
    s = table(Path("methods.rs"), "STR_METHODS")
    li = table(Path("methods.rs"), "LIST_METHODS")
    d = table(Path("methods.rs"), "DICT_METHODS")
    st = table(Path("methods.rs"), "SET_METHODS")
    by = table(Path("methods.rs"), "BYTES_METHODS")
    tu = table(Path("methods.rs"), "TUPLE_METHODS")
    fi = table(Path("methods.rs"), "FILE_METHODS")
    s_missing = table(Path("methods.rs"), "STR_MISSING")
    d_missing = table(Path("methods.rs"), "DICT_MISSING")
    st_missing = table(Path("methods.rs"), "SET_MISSING")
    by_missing = table(Path("methods.rs"), "BYTES_MISSING")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("""<!-- GENERATED by study/gen_brief.py from the engine's own tables. Do not edit. -->
# The tier-1 Python subset, exactly

You are writing a Python program that must run on a small Python interpreter.
Anything outside the list below makes the program fall back to a slower
interpreter, so stay inside it. Correctness comes first: never guess at an
approximation to stay inside the subset — a wrong answer is worse than a
fallback.

## Modules you may import

Only these: %s.

Nothing else. In particular there is **no** `re`, `collections`, `math`,
`csv`, `pathlib`, `hashlib`, `datetime`, `random`, `struct`, `base64`,
`itertools`, `functools`, `textwrap`, `glob`, `statistics`, `subprocess`,
`urllib`, `shutil`, `tempfile`, `time` or `argparse`.

## Builtins you may call

Only these %d: %s.

Names that are NOT there and are commonly reached for: `eval`, `exec`,
`getattr`, `setattr`, `hasattr`, `vars`, `dir`, `globals`, `locals`,
`frozenset`, `bytearray`, `complex`, `hash`, `id`, `callable`, `slice`,
`super`, `staticmethod`, `property`, `pow` (use `**`), `bytearray`, `memoryview`
and `object`.

## Methods you may call

* `str`: %s
* `list`: %s
* `dict`: %s
* `set`: %s
* `bytes`: %s
* `tuple`: %s
* file objects: %s

Absent and refused — `str`: %s; `dict`: %s; `set`: %s; `bytes`: %s.

## Syntax that is inside

Assignment, `if`/`elif`/`else`, `for`, `while`, `break`, `continue`, `def`
(including default arguments, `*args` and `**kwargs`), `lambda`, `return`,
`global`, `try`/`except`/`finally`, `raise`, `assert`, `with open(...) as f`,
`del`, augmented assignment, slice assignment, tuple and starred unpacking,
chained comparisons, conditional expressions, list/dict/set comprehensions,
generator expressions, f-strings including format specs, `%%` formatting,
`str.format`, bytes literals, triple-quoted strings, nested functions and
closures.

## Syntax that is outside

`class` definitions, decorators, `yield` and generator functions, `async`/
`await`, the walrus operator `:=`, keyword-only parameters (`def f(*, a)`),
`nonlocal`, self-documenting f-strings (`f"{x=}"`), `except*`, `...`
(Ellipsis), complex-number literals.

## Three refusals that no rewrite of an import can dodge

These are decided at run time, not by the imports, and they are deliberate:

1. **Integers are 64-bit.** Any arithmetic whose exact result leaves the signed
   64-bit range is refused. Factorials past 20, `2**64`, and big products are
   all outside.
2. **Set iteration order is refused.** Building a set is fine and `len(set(...))`
   is fine, but anything that would *expose* an order — printing a set,
   iterating one, `list(set(...))` — is refused. Wrap it in `sorted(...)`.
3. **`repr()` of non-ASCII text** outside a whitelist of plainly printable
   blocks is refused, and so is `os.listdir()`, whose order the filesystem
   defines rather than Python.

## The tier below, for reference

If a program leaves the subset above but only needs one of these modules, it
lands on a second small interpreter rather than on CPython: %s. That is still
much cheaper than CPython, so preferring `re` over `subprocess` is a real win
even when the subset proper is out of reach.
""" % (
        fmt(modules), len(builtins), fmt(builtins),
        fmt(s), fmt(li), fmt(d), fmt(st), fmt(by), fmt(tu), fmt(fi),
        fmt(s_missing), fmt(d_missing), fmt(st_missing), fmt(by_missing),
        fmt(mp_modules),
    ), encoding="utf-8")
    print("wrote %s (%d bytes)" % (OUT.relative_to(ROOT), OUT.stat().st_size))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
