"""Ask the model for tasks and k independent programs each. Executes nothing.

THE BOUNDARY THIS MODULE SITS ON. `HARVESTING.md` says the upstream key belongs
to the trusted controller and that the model-facing execution boundary must
never receive it. This side holds the key and therefore **runs no generated
code**: it writes candidates to JSONL and stops. :mod:`pipeline.synth` runs
them, in a job with no key. Never merge the two.

WHAT TO ASK FOR, and why it is not "ordinary tasks". The first scaled run asked
for ordinary sub-25-line Python and got 3,499 of 3,837 tasks (91.2%) already
served natively (GH run 35320962503, 2026-09-18). That is the one population
`PREREGISTRATION.md` §2 item (g) strikes out: sampling draws from "rewrite +
ceiling only, less the cases that cannot teach", because "an unobserved case is
a plain coding task the stock model already answers". Its pool is 66 rewrite to
27 ceiling, decided 2026-09-13 before any spend. We had generated the inverse.

So generation NAMES a construct the engine refuses and asks for an ordinary
task whose natural answer reaches for it. The task text never mentions the
runtime, the subset or the module: the model must write its natural first
draft, which is the refused one. Triage confirms the refusal and the repair
supplies the native rewrite, and THAT PAIR is the rewrite case.

The two lists are not interchangeable and the difference is the whole point:
  REWRITABLE    a native equivalent exists, so the pair teaches a substitution.
                Proof it exists: `repair_rules` already rewrites functools,
                statistics, heapq and string, verified byte-identical.
  UNREWRITABLE  no native equivalent exists, so the right answer KEEPS the
                import and takes the fallback. These are the ceiling cases, the
                counterweight that stops an arm scoring well by learning to
                avoid every import.

THE DOOR. Cerebras speaks the OpenAI chat shape, so this goes through
:class:`pipeline.backends.ChatBackend` like every other arm this tree measures:
stdlib ``urllib``, the same retry policy, no vendor SDK in the job. The one
knob it needs that the eval arms do not is ``reasoning_effort="none"``; see the
note on that field in ``backends.py``.

BOUNDS. "Concurrency is not a spending limit" (`HARVESTING.md`): calls, output
tokens and wall time are all capped, the run is resumable, and every refusal,
rate limit and transport error is written down rather than retried into
silence. Library code: the loop takes a backend and a sink and returns its
ledger; ``cli.py`` owns the files and the exit code.
"""

from __future__ import annotations

import datetime as _dt
import json
import os
import random
import re
import time
from collections import Counter
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from .backends import BackendError, ChatBackend

#: `harvesting/worker.py` pins this and `harvesting/preflight.py` refuses a
#: substitution. Same model here, for the same reason: a bank generated by a
#: different model is a different bank. It is also the model being trained, so
#: this is on-policy rejection sampling, not distillation from a stronger
#: teacher, and no result here says a better teacher would not do better.
MODEL = "qwen-3.8-27b"
CEREBRAS_BASE_URL = "https://api.cerebras.ai/v1"

#: `PREREGISTRATION.md` §2 item (g): 66 rewrite to 27 ceiling, decided before
#: the spend. The target is drawn in that proportion rather than dropping the
#: counterweight.
REWRITE_FRACTION = 66.0 / 93.0

REWRITABLE = [
    ("functools.reduce", "folding a list down to one value"),
    ("itertools.groupby", "grouping consecutive equal keys in a sorted list"),
    ("itertools.combinations", "every unordered pair or triple drawn from a list"),
    ("statistics.median", "the middle value of a set of measurements"),
    ("statistics.mean", "an average of numbers"),
    ("heapq.nsmallest", "the few smallest items without sorting everything"),
    ("heapq.heappush and heapq.heappop", "a priority queue processed in order"),
    ("bisect.bisect_left", "where a value belongs in a sorted list"),
    ("operator.itemgetter", "sorting records by a chosen field"),
    ("collections.deque", "a sliding window or a queue consumed from both ends"),
    ("collections.OrderedDict", "entries kept in insertion order and re-ordered"),
    ("copy.deepcopy", "an independent copy of nested data before mutating it"),
    ("string.ascii_lowercase", "a rotation or substitution cipher over the alphabet"),
    ("textwrap.fill", "wrapping prose to a fixed column width"),
    ("math.comb", "counting combinations or binomial coefficients"),
    ("math.prod", "the product of a list of numbers"),
    ("math.lcm", "a least common multiple of several integers"),
    ("str.center or str.ljust with a fill character", "a fixed-width aligned report"),
    ("str.translate with str.maketrans", "replacing many characters at once"),
    ("dict.fromkeys", "de-duplicating while preserving order"),
    ("calendar.monthrange", "how many days a given month has"),
    ("datetime.date arithmetic", "days between two dates, or a date N days on"),
    ("array.array", "a compact numeric buffer"),
    ("csv.writer", "emitting correctly quoted CSV"),
    ("io.StringIO", "building text in memory and reading it back"),
    ("frozenset", "a set used as a dictionary key"),
    ("zip with strict=True", "pairing two lists that must be the same length"),
]

UNREWRITABLE = [
    # Moved here from REWRITABLE on 2026-09-18 after the repair failed: both
    # need a user-defined type, and `lypning-l -c "class C: ..."` exits 90 with
    # `class: class definition`. A shim that cannot be native is not a rewrite.
    ("fractions.Fraction", "exact rational arithmetic without floating point"),
    ("collections.namedtuple", "records with named fields"),
    ("unicodedata.name or unicodedata.category", "naming or classifying characters"),
    ("time.strftime or time.gmtime", "formatting a timestamp"),
    ("uuid.uuid5", "a deterministic namespaced identifier"),
    ("difflib.ndiff or difflib.SequenceMatcher", "a textual diff or similarity ratio"),
    ("math.log10, math.exp or math.sin", "logarithms or trigonometry"),
    ("base64.b32encode", "base32 encoding"),
    ("hashlib.new with an algorithm name", "a digest chosen at run time"),
    ("random.shuffle with a fixed seed", "a deterministic shuffle"),
]

TASK_PROMPT = """Invent {n} small Python programming tasks whose most natural solution uses
{construct} — for example, {hint}.

Rules for every task:
- State plainly what the program must do and where its input comes from: stdin, or
  command-line arguments, or a named text file.
- Its entire output is deterministic UTF-8 text on stdout. Nothing random, no clocks,
  no network, no file writing, no reading of anything not named in the task.
- The expected output is fully determined by the input and the task text alone.
- Write the task as an ORDINARY request. Do NOT mention {construct}, any module name,
  any library, or any restriction on how it must be solved. A competent Python
  programmer reading it should simply reach for {construct} on their own.
- Tasks must differ from each other in what they compute, not only in wording.

Reply with ONLY a JSON array of objects, each {{"task": "<one paragraph>",
"inputs": [<4 distinct inputs>]}}. Each input is an object with any of
"stdin" (string), "argv" (array of strings), "files" (object of name to content).
Include at least one empty or boundary input. No prose, no code fences."""

SOLVE_PROMPT = """Write a Python 3 program for this task.

{task}

Constraints: read only from the sources the task names; write only to stdout;
be deterministic; use the standard library only. Write the solution you would
naturally write — do not avoid any module or restrict yourself to builtins.
Reply with ONLY the program source. No explanation, no markdown fences."""

#: Six consecutive task calls that yielded no usable task means the prompt or
#: the model contract is wrong, not that the next call will be luckier. The
#: first run learned this the expensive way, at 60 calls for 0 tasks.
BARREN_LIMIT = 6

_HTTP = re.compile(r"HTTP (\d{3})")


def backend_from_env(env: Optional[Dict[str, str]] = None, *, timeout_s: float = 120.0,
                     base_url: str = CEREBRAS_BASE_URL) -> Optional[ChatBackend]:
    """The Cerebras door, or None when the key is not in this process.

    ``.strip()`` is not cosmetic: a secret stored with a trailing newline
    produces an Authorization header the API rejects with 403, which reads
    exactly like a revoked key and sends you looking in the wrong place.
    """
    key = (env if env is not None else os.environ).get("CEREBRAS_API_KEY", "").strip()
    if not key:
        return None
    return ChatBackend(base_url=base_url, model=MODEL, api_key=key, timeout_s=timeout_s,
                       max_retries=2)


def call(backend: ChatBackend, messages: List[Dict[str, str]], *, max_tokens: int,
         temperature: float, ledger: Counter) -> Tuple[Optional[str], Optional[str]]:
    """One bounded completion: ``(content, None)`` or ``(None, why)``.

    Every non-answer is an outcome in the ledger, never a retry loop of ours —
    the backend already retried 429 and 5xx. Exception bodies are never logged:
    they can echo the request, and some error shapes carry the Authorization
    header with them.
    """
    try:
        done = backend.complete(messages, temperature=temperature, top_p=0.8,
                                max_tokens=max_tokens, reasoning_effort="none")
    except BackendError as exc:
        m = _HTTP.search(str(exc))
        label = ("http-%s" % m.group(1)) if m else "transport"
        ledger[label.replace("-", "_")] += 1
        return None, label
    ledger["calls"] += 1
    ledger["output_tokens"] += done.completion_tokens
    ledger["input_tokens"] += done.prompt_tokens
    if done.finish_reason == "length":
        ledger["truncated"] += 1
        return None, "truncated"
    if not done.text.strip():
        # A successful call with no content is a failure that looks like a
        # success. Name it, so a budget cannot drain into empty replies.
        ledger["empty_content"] += 1
        return None, "empty-content"
    return done.text, None


def strip_fence(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9]*\n", "", text)
        text = re.sub(r"\n```$", "", text.strip())
    return text.strip()


def parse_tasks(text: str) -> List[Dict[str, Any]]:
    """The usable ``{"task", "inputs"}`` objects in a reply, and nothing else."""
    text = strip_fence(text or "")
    start, end = text.find("["), text.rfind("]")
    if start < 0 or end <= start:
        return []
    try:
        rows = json.loads(text[start:end + 1])
    except ValueError:
        return []
    out = []
    for r in rows if isinstance(rows, list) else []:
        if not isinstance(r, dict):
            continue
        task, inputs = r.get("task"), r.get("inputs")
        if not isinstance(task, str) or len(task.strip()) < 30:
            continue
        if not isinstance(inputs, list) or len(inputs) < 3:
            continue
        clean = []
        for spec in inputs[:6]:
            if not isinstance(spec, dict):
                continue
            item: Dict[str, Any] = {}
            if isinstance(spec.get("stdin"), str):
                item["stdin"] = spec["stdin"]
            if isinstance(spec.get("argv"), list) and all(
                    isinstance(a, str) for a in spec["argv"]):
                item["argv"] = spec["argv"]
            files = spec.get("files")
            if isinstance(files, dict) and all(
                    isinstance(k, str) and isinstance(v, str) for k, v in files.items()):
                item["files"] = files
            if item:
                clean.append(item)
        if len(clean) >= 3:
            out.append({"task": task.strip(), "inputs": clean})
    return out


def seen_tasks(rows: Iterable[Any]) -> set:
    """The task texts in already-written rows, tolerating rows that are not ours."""
    out = set()
    for row in rows:
        if isinstance(row, dict) and isinstance(row.get("task"), str):
            out.add(row["task"])
    return out


class Budget:
    """Calls, output tokens and wall time. Whichever runs out first ends the run."""

    def __init__(self, *, max_calls: int, max_output_tokens: int, max_seconds: float,
                 clock: Callable[[], float] = time.time) -> None:
        self.max_calls = int(max_calls)
        self.max_output_tokens = int(max_output_tokens)
        self.max_seconds = float(max_seconds)
        self.clock = clock
        self.started = clock()

    def elapsed(self) -> float:
        return self.clock() - self.started

    def left(self, ledger: Counter) -> bool:
        return (ledger["calls"] < self.max_calls
                and ledger["output_tokens"] < self.max_output_tokens
                and self.elapsed() < self.max_seconds)

    def stopped_because(self, ledger: Counter) -> str:
        if ledger["calls"] >= self.max_calls:
            return "calls"
        if ledger["output_tokens"] >= self.max_output_tokens:
            return "tokens"
        if self.elapsed() >= self.max_seconds:
            return "time"
        return "provider"


def generate(backend: ChatBackend, sink: Callable[[Dict[str, Any]], None], *, budget: Budget,
             seen: set, samples: int = 3, tasks_per_call: int = 8,
             rewrite_fraction: float = REWRITE_FRACTION, rng: Optional[random.Random] = None,
             today: Optional[str] = None) -> Dict[str, Any]:
    """Draw constructs, ask for tasks, answer each k times, hand rows to ``sink``.

    ``seen`` is mutated: every task written is added, so a resumed run and the
    banked history both stop a task from being paid for twice. Returns the
    summary a report quotes: what was written, the ledger, and why it stopped.
    """
    rng = rng or random.Random(1111)
    ledger: Counter = Counter()
    when = today or _dt.date.today().isoformat()
    barren = 0
    written = 0
    while budget.left(ledger):
        want_rewrite = rng.random() < rewrite_fraction
        pool = REWRITABLE if want_rewrite else UNREWRITABLE
        construct, hint = pool[rng.randrange(len(pool))]
        stratum = "rewrite" if want_rewrite else "ceiling"
        ledger["asked_" + stratum] += 1
        text, err = call(backend, [{"role": "user", "content": TASK_PROMPT.format(
            n=tasks_per_call, construct=construct, hint=hint)}],
            max_tokens=4096, temperature=0.9, ledger=ledger)
        if err:
            ledger["task_call_failed"] += 1
            barren += 1
            if err.startswith("http-4") and err != "http-429":
                # Rejected, not rate-limited: the key or the entitlement, and
                # the next call will not be different.
                ledger["stopped_rejected"] = 1
                break
            if barren >= BARREN_LIMIT:
                ledger["stopped_barren"] = 1
                break
            continue
        tasks = parse_tasks(text or "")
        ledger["tasks_parsed"] += len(tasks)
        barren = 0 if tasks else barren + 1
        if barren >= BARREN_LIMIT:
            ledger["stopped_barren"] = 1
            break
        for spec in tasks:
            if not budget.left(ledger):
                break
            if spec["task"] in seen:
                ledger["duplicate_task"] += 1
                continue
            programs = []
            for _ in range(samples):
                if not budget.left(ledger):
                    break
                src, perr = call(
                    backend, [{"role": "user", "content": SOLVE_PROMPT.format(task=spec["task"])}],
                    max_tokens=1536, temperature=0.7, ledger=ledger)
                if perr:
                    ledger["solve_failed"] += 1
                    continue
                src = strip_fence(src or "")
                if src:
                    programs.append(src)
            if len(programs) < 2:
                # Fewer than two samples cannot agree with anything, so the row
                # has no oracle and is not worth storing as a candidate.
                ledger["too_few_samples"] += 1
                continue
            seen.add(spec["task"])
            sink({"task": spec["task"], "inputs": spec["inputs"], "programs": programs,
                  "domain": stratum + ":" + construct.split(".")[0].split()[0],
                  "model": backend.model, "target_construct": construct,
                  "stratum": stratum, "generated_on": when})
            written += 1
    return {"written_this_run": written, "tasks_total": len(seen),
            "elapsed_s": round(budget.elapsed(), 1), "ledger": dict(sorted(ledger.items())),
            "stopped_because": budget.stopped_because(ledger)}
