"""Generate candidate tasks and programs from Qwen on Cerebras. Executes nothing.

THE BOUNDARY THIS FILE SITS ON. `HARVESTING.md` says the upstream key belongs to
the trusted controller and that the model-facing execution boundary must never
receive it. This process holds the key and therefore **runs no generated code**:
it writes candidates to JSONL and stops. `triage.py` runs them, in a job with no
key. Never merge the two.

WHAT THE ORACLE IS, AND IS NOT. Deriving expected output by running the model's
own program is copying the answer, which `ORCHESTRATION.md` step 4 forbids. So
each task is answered **k times independently** and a case survives only when at
least `--agree` of those samples produce byte-identical stdout on every input.
That is self-consistency across independent samples: real evidence, and much
stronger than one program, but it is NOT independent derivation from the task.
Samples share a model and a prompt, so they share a misreading. Rows from here
carry `oracle_basis: self-consistency` and must be reported as a weaker tier
than the authored `bank_v2`, never merged into one number.

The teacher is `qwen-3.8-27b` — the model being trained. This is on-policy
rejection sampling, not distillation from a stronger teacher, and no result here
is evidence that a better teacher would not do better.

BOUNDS. "Concurrency is not a spending limit" (`HARVESTING.md`): calls, output
tokens and wall time are all capped, the run is resumable, and every refusal,
rate-limit and transport error is written down rather than retried into silence.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ENDPOINT = "https://api.cerebras.ai/v1/chat/completions"
#: `harvesting/worker.py` pins this and `harvesting/preflight.py` refuses a
#: substitution. Same model here, for the same reason: a bank generated by a
#: different model is a different bank.
MODEL = "qwen-3.8-27b"

DOMAINS = [
    ("text", "parsing, normalising and reporting on lines of text"),
    ("records", "tabular records: grouping, filtering, joining, validating"),
    ("numbers", "integer and rational arithmetic, counting, accumulation"),
    ("sequences", "ordering, deduplicating, windowing and chunking sequences"),
    ("encoding", "base conversion, escaping, checksums, fixed-width formatting"),
    ("files", "reading one or more small text files and summarising them"),
    ("argv", "command-line arguments that select or parameterise the work"),
    ("validation", "checking input against a stated rule and reporting which failed"),
    ("dates", "day/month arithmetic done from first principles, no date library"),
    ("stats", "counts, extremes, medians and simple aggregates over numbers"),
]

TASK_PROMPT = """Invent {n} small, self-contained Python programming tasks about {topic}.

Rules for every task:
- It reads from stdin, or command-line arguments, or a named text file - state which.
- Its entire output is deterministic UTF-8 text on stdout. No randomness, no clocks,
  no network, no file writing.
- It is solvable in under 25 lines of ordinary Python.
- The expected output is fully determined by the input and the task text alone.
- Tasks must differ from each other in what they compute, not only in wording.

Reply with ONLY a JSON array of objects, each {{"task": "<one paragraph>",
"inputs": [<4 distinct inputs>]}}. Each input is an object with any of
"stdin" (string), "argv" (array of strings), "files" (object of name to content).
Include at least one empty or boundary input. No prose, no code fences."""

SOLVE_PROMPT = """Write a Python 3 program for this task.

{task}

Constraints: read only from the sources the task names; write only to stdout;
be deterministic; use the standard library only. Reply with ONLY the program
source. No explanation, no markdown fences."""


def post(key, payload, timeout):
    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        ENDPOINT, data=body, method="POST",
        headers={"Authorization": "Bearer " + key, "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def call(key, messages, *, max_tokens, temperature, timeout, ledger):
    """One bounded completion. Every non-answer is an outcome, not a retry loop."""
    payload = {"model": MODEL, "messages": messages, "temperature": temperature,
               "top_p": 0.8, "max_completion_tokens": max_tokens}
    for attempt in range(3):
        try:
            data = post(key, payload, timeout)
        except urllib.error.HTTPError as exc:
            # Never log the body: it can echo the request, and the request
            # carries the Authorization header in some proxies' error shapes.
            ledger["http_%d" % exc.code] = ledger.get("http_%d" % exc.code, 0) + 1
            if exc.code in (429, 500, 502, 503, 504) and attempt < 2:
                time.sleep(2 ** attempt * 5)
                continue
            return None, "http-%d" % exc.code
        except Exception as exc:                                  # noqa: BLE001
            ledger["transport"] = ledger.get("transport", 0) + 1
            if attempt < 2:
                time.sleep(2 ** attempt * 5)
                continue
            return None, type(exc).__name__
        usage = data.get("usage") or {}
        ledger["calls"] = ledger.get("calls", 0) + 1
        ledger["output_tokens"] = ledger.get("output_tokens", 0) + int(
            usage.get("completion_tokens") or 0)
        ledger["input_tokens"] = ledger.get("input_tokens", 0) + int(
            usage.get("prompt_tokens") or 0)
        choice = (data.get("choices") or [{}])[0]
        if choice.get("finish_reason") == "length":
            ledger["truncated"] = ledger.get("truncated", 0) + 1
            return None, "truncated"
        return (choice.get("message") or {}).get("content") or "", None
    return None, "exhausted"


def strip_fence(text):
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9]*\n", "", text)
        text = re.sub(r"\n```$", "", text.strip())
    return text.strip()


def parse_tasks(text):
    text = strip_fence(text)
    start, end = text.find("["), text.rfind("]")
    if start < 0 or end <= start:
        return []
    try:
        rows = json.loads(text[start:end + 1])
    except ValueError:
        return []
    out = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        task, inputs = r.get("task"), r.get("inputs")
        if not isinstance(task, str) or len(task.strip()) < 30:
            continue
        if not isinstance(inputs, list) or len(inputs) < 3:
            continue
        clean = []
        for spec in inputs[:6]:
            if not isinstance(spec, dict):
                continue
            item = {}
            if isinstance(spec.get("stdin"), str):
                item["stdin"] = spec["stdin"]
            if isinstance(spec.get("argv"), list) and all(
                    isinstance(a, str) for a in spec["argv"]):
                item["argv"] = spec["argv"]
            files = spec.get("files")
            if isinstance(files, dict) and all(
                    isinstance(k, str) and isinstance(v, str) for k, v in files.items()):
                item["files"] = files
            if item:
                clean.append(item)
        if len(clean) >= 3:
            out.append({"task": task.strip(), "inputs": clean})
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--tasks-per-call", type=int, default=8)
    ap.add_argument("--samples", type=int, default=3,
                    help="independent programs per task; the self-consistency k")
    ap.add_argument("--max-calls", type=int, default=200)
    ap.add_argument("--max-output-tokens", type=int, default=1_500_000)
    ap.add_argument("--max-minutes", type=float, default=50.0)
    ap.add_argument("--timeout", type=float, default=120.0)
    ap.add_argument("--seed", type=int, default=1111)
    args = ap.parse_args()

    key = os.environ.get("CEREBRAS_API_KEY", "")
    if not key:
        print("CEREBRAS_API_KEY is not set; this runs on the trusted controller only",
              file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Resumable: a run that hits its bound is a normal outcome, and the next run
    # must not re-pay for what this one already produced.
    seen = set()
    if args.output.exists():
        for line in args.output.read_text(encoding="utf-8").splitlines():
            if line.strip():
                seen.add(json.loads(line)["task"])
    print("resuming with %d task(s) already generated" % len(seen))

    rng = random.Random(args.seed)
    ledger = {}
    started = time.time()
    written = 0

    def budget_left():
        return (ledger.get("calls", 0) < args.max_calls
                and ledger.get("output_tokens", 0) < args.max_output_tokens
                and (time.time() - started) < args.max_minutes * 60)

    with args.output.open("a", encoding="utf-8") as sink:
        while budget_left():
            name, topic = DOMAINS[rng.randrange(len(DOMAINS))]
            text, err = call(key, [{"role": "user", "content": TASK_PROMPT.format(
                n=args.tasks_per_call, topic=topic)}],
                max_tokens=4096, temperature=0.9, timeout=args.timeout, ledger=ledger)
            if err:
                ledger["task_call_failed"] = ledger.get("task_call_failed", 0) + 1
                if err.startswith("http-4") and err != "http-429":
                    break
                continue
            tasks = parse_tasks(text or "")
            ledger["tasks_parsed"] = ledger.get("tasks_parsed", 0) + len(tasks)
            for spec in tasks:
                if not budget_left():
                    break
                if spec["task"] in seen:
                    ledger["duplicate_task"] = ledger.get("duplicate_task", 0) + 1
                    continue
                programs = []
                for _ in range(args.samples):
                    if not budget_left():
                        break
                    src, perr = call(
                        key, [{"role": "user", "content": SOLVE_PROMPT.format(task=spec["task"])}],
                        max_tokens=1536, temperature=0.7, timeout=args.timeout, ledger=ledger)
                    if perr:
                        ledger["solve_failed"] = ledger.get("solve_failed", 0) + 1
                        continue
                    src = strip_fence(src or "")
                    if src:
                        programs.append(src)
                if len(programs) < 2:
                    # Fewer than two samples cannot agree with anything, so the
                    # row has no oracle and is not worth storing as a candidate.
                    ledger["too_few_samples"] = ledger.get("too_few_samples", 0) + 1
                    continue
                seen.add(spec["task"])
                sink.write(json.dumps({
                    "task": spec["task"], "inputs": spec["inputs"],
                    "programs": programs, "domain": name, "model": MODEL,
                }, sort_keys=True) + "\n")
                sink.flush()
                written += 1

    elapsed = time.time() - started
    print(json.dumps({
        "written_this_run": written, "tasks_total": len(seen),
        "elapsed_s": round(elapsed, 1), "ledger": ledger,
        "stopped_because": ("calls" if ledger.get("calls", 0) >= args.max_calls else
                            "tokens" if ledger.get("output_tokens", 0) >= args.max_output_tokens
                            else "time" if elapsed >= args.max_minutes * 60 else "provider"),
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
