"""Generate candidate tasks and programs from Qwen on Cerebras. Executes nothing.

THE BOUNDARY THIS FILE SITS ON. `HARVESTING.md` says the upstream key belongs to
the trusted controller and that the model-facing execution boundary must never
receive it. This process holds the key and therefore **runs no generated code**:
it writes candidates to JSONL and stops. `triage.py` runs them, in a job with no
key. Never merge the two.

WHAT THE ORACLE IS, AND IS NOT. Deriving expected output by running the model's
own program is copying the answer, which `ORCHESTRATION.md` step 4 forbids. So
each task is answered **k times independently** and a case survives only when at
least `--agree` of those samples produce byte-identical stdout on every input.
That is self-consistency across independent samples: real evidence, and much
stronger than one program, but it is NOT independent derivation from the task.
Samples share a model and a prompt, so they share a misreading. Rows from here
carry `oracle_basis: self-consistency` and must be reported as a weaker tier
than the authored `bank_v2`, never merged into one number.

The teacher is `qwen-3.8-27b` — the model being trained. This is on-policy
rejection sampling, not distillation from a stronger teacher, and no result here
is evidence that a better teacher would not do better.

BOUNDS. "Concurrency is not a spending limit" (`HARVESTING.md`): calls, output
tokens and wall time are all capped, the run is resumable, and every refusal,
rate-limit and transport error is written down rather than retried into silence.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
from pathlib import Path

#: `harvesting/worker.py` pins this and `harvesting/preflight.py` refuses a
#: substitution. Same model here, for the same reason: a bank generated by a
#: different model is a different bank.
MODEL = "qwen-3.8-27b"

# --------------------------------------------------------------------------
# WHAT TO ASK FOR, and why it is not "ordinary tasks".
#
# The first scaled run asked for ordinary sub-25-line Python and got 3,499 of
# 3,837 tasks (91.2%) already served natively (GH run 35320962503, 2026-09-18).
# That is the one population `PREREGISTRATION.md` §2g strikes out: sampling
# draws from "rewrite + ceiling only, less the cases that cannot teach", because
# "an unobserved case is a plain coding task the stock model already answers".
# Its pool is 66 rewrite to 27 ceiling — 71/29 — decided 2026-09-13 before any
# spend. We generated the inverse.
#
# So generation now NAMES a construct the engine refuses and asks for an
# ordinary task whose natural answer reaches for it. The task text never
# mentions lypning, the subset, or the module: the model must write its natural
# first draft, which is the refused one. `triage.py` confirms the refusal and
# `repair.py` supplies the native rewrite, and THAT PAIR is the rewrite case.
#
# The two lists are not interchangeable and the difference is the whole point:
#   REWRITABLE   a native equivalent exists, so the pair teaches a substitution.
#                Proof it exists: repair.py already rewrites functools,
#                statistics, heapq and string, verified byte-identical.
#   UNREWRITABLE no native equivalent exists, so the right answer KEEPS the
#                import and takes the fallback. These are the ceiling cases, and
#                they are the counterweight that stops an arm scoring well by
#                learning to avoid every import.
#
# bank v2's ten "fallback-control" families are all on the REWRITABLE list, so
# they taught "fall back where a native answer exists" — the behaviour the round
# exists to remove. They are controls in name only.

REWRITABLE = [
    ("functools.reduce", "folding a list down to one value"),
    ("itertools.groupby", "grouping consecutive equal keys in a sorted list"),
    ("itertools.combinations", "every unordered pair or triple drawn from a list"),
    ("statistics.median", "the middle value of a set of measurements"),
    ("statistics.mean", "an average of numbers"),
    ("heapq.nsmallest", "the few smallest items without sorting everything"),
    ("heapq.heappush and heapq.heappop", "a priority queue processed in order"),
    ("bisect.bisect_left", "where a value belongs in a sorted list"),
    ("operator.itemgetter", "sorting records by a chosen field"),
    ("collections.deque", "a sliding window or a queue consumed from both ends"),
    ("collections.OrderedDict", "entries kept in insertion order and re-ordered"),
    ("copy.deepcopy", "an independent copy of nested data before mutating it"),
    ("string.ascii_lowercase", "a rotation or substitution cipher over the alphabet"),
    ("textwrap.fill", "wrapping prose to a fixed column width"),
    ("math.comb", "counting combinations or binomial coefficients"),
    ("math.prod", "the product of a list of numbers"),
    ("math.lcm", "a least common multiple of several integers"),
    ("str.center or str.ljust with a fill character", "a fixed-width aligned report"),
    ("str.translate with str.maketrans", "replacing many characters at once"),
    ("dict.fromkeys", "de-duplicating while preserving order"),
    ("calendar.monthrange", "how many days a given month has"),
    ("datetime.date arithmetic", "days between two dates, or a date N days on"),
    ("array.array", "a compact numeric buffer"),
    ("csv.writer", "emitting correctly quoted CSV"),
    ("io.StringIO", "building text in memory and reading it back"),
    ("frozenset", "a set used as a dictionary key"),
    ("zip with strict=True", "pairing two lists that must be the same length"),
]

UNREWRITABLE = [
    # Moved here from REWRITABLE on 2026-09-18 after the repair failed: both
    # need a user-defined type, and `lypning-l -c "class C: ..."` exits 90 with
    # `class: class definition`. A shim that cannot be native is not a rewrite.
    ("fractions.Fraction", "exact rational arithmetic without floating point"),
    ("collections.namedtuple", "records with named fields"),
    ("unicodedata.name or unicodedata.category", "naming or classifying characters"),
    ("time.strftime or time.gmtime", "formatting a timestamp"),
    ("uuid.uuid5", "a deterministic namespaced identifier"),
    ("difflib.ndiff or difflib.SequenceMatcher", "a textual diff or similarity ratio"),
    ("math.log10, math.exp or math.sin", "logarithms or trigonometry"),
    ("base64.b32encode", "base32 encoding"),
    ("hashlib.new with an algorithm name", "a digest chosen at run time"),
    ("random.shuffle with a fixed seed", "a deterministic shuffle"),
]

TASK_PROMPT = """Invent {n} small Python programming tasks whose most natural solution uses
{construct} — for example, {hint}.

Rules for every task:
- State plainly what the program must do and where its input comes from: stdin, or
  command-line arguments, or a named text file.
- Its entire output is deterministic UTF-8 text on stdout. Nothing random, no clocks,
  no network, no file writing, no reading of anything not named in the task.
- The expected output is fully determined by the input and the task text alone.
- Write the task as an ORDINARY request. Do NOT mention {construct}, any module name,
  any library, or any restriction on how it must be solved. A competent Python
  programmer reading it should simply reach for {construct} on their own.
- Tasks must differ from each other in what they compute, not only in wording.

Reply with ONLY a JSON array of objects, each {{"task": "<one paragraph>",
"inputs": [<4 distinct inputs>]}}. Each input is an object with any of
"stdin" (string), "argv" (array of strings), "files" (object of name to content).
Include at least one empty or boundary input. No prose, no code fences."""

SOLVE_PROMPT = """Write a Python 3 program for this task.

{task}

Constraints: read only from the sources the task names; write only to stdout;
be deterministic; use the standard library only. Write the solution you would
naturally write — do not avoid any module or restrict yourself to builtins.
Reply with ONLY the program source. No explanation, no markdown fences."""


def make_client():
    """The official SDK. `.strip()` is not cosmetic: a secret stored with a
    trailing newline produces an Authorization header the API rejects with 403,
    which reads exactly like a revoked key and sends you looking in the wrong
    place."""
    from cerebras.cloud.sdk import Cerebras

    key = os.environ.get("CEREBRAS_API_KEY", "").strip()
    if not key:
        return None
    return Cerebras(api_key=key)


def _status_of(exc):
    """The HTTP status an SDK exception carries, if it carries one."""
    for attr in ("status_code", "status"):
        value = getattr(exc, attr, None)
        if isinstance(value, int):
            return value
    response = getattr(exc, "response", None)
    code = getattr(response, "status_code", None)
    return code if isinstance(code, int) else None


def call(client, messages, *, max_tokens, temperature, timeout, ledger):
    """One bounded completion. Every non-answer is an outcome, not a retry loop."""
    for attempt in range(3):
        try:
            # `reasoning_effort` is not optional for this model. Qwen3.8 puts
            # its thinking in a separate channel and leaves `content` EMPTY when
            # reasoning is on, so omitting this returns a successful call with
            # nothing in it — which is how the first run spent all 60 calls and
            # wrote 0 tasks. `harvesting/proxy.py` always sets it, default none.
            data = client.chat.completions.create(
                messages=messages, model=MODEL, temperature=temperature,
                top_p=0.8, max_completion_tokens=max_tokens, timeout=timeout,
                reasoning_effort="none")
        except Exception as exc:                                  # noqa: BLE001
            # Never log the exception body: it can echo the request, and some
            # error shapes carry the Authorization header with it.
            code = _status_of(exc)
            label = ("http_%d" % code) if code else "transport"
            ledger[label] = ledger.get(label, 0) + 1
            retryable = code in (429, 500, 502, 503, 504) or code is None
            if retryable and attempt < 2:
                time.sleep(2 ** attempt * 5)
                continue
            return None, (("http-%d" % code) if code else type(exc).__name__)
        usage = getattr(data, "usage", None)
        ledger["calls"] = ledger.get("calls", 0) + 1
        ledger["output_tokens"] = ledger.get("output_tokens", 0) + int(
            getattr(usage, "completion_tokens", 0) or 0)
        ledger["input_tokens"] = ledger.get("input_tokens", 0) + int(
            getattr(usage, "prompt_tokens", 0) or 0)
        choices = getattr(data, "choices", None) or []
        if not choices:
            ledger["no_choices"] = ledger.get("no_choices", 0) + 1
            return None, "no-choices"
        choice = choices[0]
        if getattr(choice, "finish_reason", None) == "length":
            ledger["truncated"] = ledger.get("truncated", 0) + 1
            return None, "truncated"
        content = getattr(getattr(choice, "message", None), "content", None) or ""
        if not content.strip():
            # A successful call with no content is a failure that looks like a
            # success. Name it, so a budget cannot drain into empty replies.
            ledger["empty_content"] = ledger.get("empty_content", 0) + 1
            return None, "empty-content"
        return content, None
    return None, "exhausted"


def strip_fence(text):
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9]*\n", "", text)
        text = re.sub(r"\n```$", "", text.strip())
    return text.strip()


def parse_tasks(text):
    text = strip_fence(text)
    start, end = text.find("["), text.rfind("]")
    if start < 0 or end <= start:
        return []
    try:
        rows = json.loads(text[start:end + 1])
    except ValueError:
        return []
    out = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        task, inputs = r.get("task"), r.get("inputs")
        if not isinstance(task, str) or len(task.strip()) < 30:
            continue
        if not isinstance(inputs, list) or len(inputs) < 3:
            continue
        clean = []
        for spec in inputs[:6]:
            if not isinstance(spec, dict):
                continue
            item = {}
            if isinstance(spec.get("stdin"), str):
                item["stdin"] = spec["stdin"]
            if isinstance(spec.get("argv"), list) and all(
                    isinstance(a, str) for a in spec["argv"]):
                item["argv"] = spec["argv"]
            files = spec.get("files")
            if isinstance(files, dict) and all(
                    isinstance(k, str) and isinstance(v, str) for k, v in files.items()):
                item["files"] = files
            if item:
                clean.append(item)
        if len(clean) >= 3:
            out.append({"task": task.strip(), "inputs": clean})
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--tasks-per-call", type=int, default=8)
    ap.add_argument("--samples", type=int, default=3,
                    help="independent programs per task; the self-consistency k")
    ap.add_argument("--max-calls", type=int, default=200)
    ap.add_argument("--max-output-tokens", type=int, default=1_500_000)
    ap.add_argument("--max-minutes", type=float, default=50.0)
    ap.add_argument("--timeout", type=float, default=120.0)
    ap.add_argument("--seed", type=int, default=1111)
    ap.add_argument("--rewrite-fraction", type=float, default=66.0 / 93.0,
                    help="share of requests aimed at a REWRITABLE construct; the "
                         "preregistered pool is 66 rewrite to 27 ceiling (0.71)")
    ap.add_argument("--exclude-tasks", type=Path,
                    help="JSONL of already-banked {'task': ...}; never regenerate these")
    args = ap.parse_args()

    client = make_client()
    if client is None:
        print("CEREBRAS_API_KEY is not set; this runs on the trusted controller only",
              file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Resumable: a run that hits its bound is a normal outcome, and the next run
    # must not re-pay for what this one already produced.
    seen = set()
    if args.output.exists():
        for line in args.output.read_text(encoding="utf-8").splitlines():
            if line.strip():
                seen.add(json.loads(line)["task"])
    banked = 0
    if args.exclude_tasks and args.exclude_tasks.is_file():
        for line in args.exclude_tasks.read_text(encoding="utf-8").splitlines():
            if line.strip():
                try:
                    seen.add(json.loads(line)["task"])
                    banked += 1
                except (ValueError, KeyError):
                    continue
    print("resuming with %d task(s) in this file, %d already banked elsewhere"
          % (len(seen) - banked, banked))

    rng = random.Random(args.seed)
    ledger = {}
    barren = 0
    started = time.time()
    written = 0

    def budget_left():
        return (ledger.get("calls", 0) < args.max_calls
                and ledger.get("output_tokens", 0) < args.max_output_tokens
                and (time.time() - started) < args.max_minutes * 60)

    with args.output.open("a", encoding="utf-8") as sink:
        while budget_left():
            # `PREREGISTRATION.md` §2g: 66 rewrite to 27 ceiling, decided before
            # the spend. Draw the target in that proportion rather than dropping
            # the counterweight, which is what makes an arm look good by
            # learning to avoid every import.
            want_rewrite = rng.random() < args.rewrite_fraction
            pool = REWRITABLE if want_rewrite else UNREWRITABLE
            construct, hint = pool[rng.randrange(len(pool))]
            name = ("rewrite:" if want_rewrite else "ceiling:") + construct.split(".")[0].split()[0]
            ledger["asked_" + ("rewrite" if want_rewrite else "ceiling")] = ledger.get(
                "asked_" + ("rewrite" if want_rewrite else "ceiling"), 0) + 1
            text, err = call(client, [{"role": "user", "content": TASK_PROMPT.format(
                n=args.tasks_per_call, construct=construct, hint=hint)}],
                max_tokens=4096, temperature=0.9, timeout=args.timeout, ledger=ledger)
            if err:
                ledger["task_call_failed"] = ledger.get("task_call_failed", 0) + 1
                barren += 1
                if err.startswith("http-4") and err != "http-429":
                    break
                # Six consecutive task calls that yielded no usable task means
                # the prompt or the model contract is wrong, not that the next
                # call will be luckier. The first run learned this the
                # expensive way, at 60 calls for 0 tasks.
                if barren >= 6:
                    ledger["stopped_barren"] = 1
                    break
                continue
            tasks = parse_tasks(text or "")
            ledger["tasks_parsed"] = ledger.get("tasks_parsed", 0) + len(tasks)
            barren = 0 if tasks else barren + 1
            if barren >= 6:
                ledger["stopped_barren"] = 1
                break
            for spec in tasks:
                if not budget_left():
                    break
                if spec["task"] in seen:
                    ledger["duplicate_task"] = ledger.get("duplicate_task", 0) + 1
                    continue
                programs = []
                for _ in range(args.samples):
                    if not budget_left():
                        break
                    src, perr = call(
                        client, [{"role": "user", "content": SOLVE_PROMPT.format(task=spec["task"])}],
                        max_tokens=1536, temperature=0.7, timeout=args.timeout, ledger=ledger)
                    if perr:
                        ledger["solve_failed"] = ledger.get("solve_failed", 0) + 1
                        continue
                    src = strip_fence(src or "")
                    if src:
                        programs.append(src)
                if len(programs) < 2:
                    # Fewer than two samples cannot agree with anything, so the
                    # row has no oracle and is not worth storing as a candidate.
                    ledger["too_few_samples"] = ledger.get("too_few_samples", 0) + 1
                    continue
                seen.add(spec["task"])
                sink.write(json.dumps({
                    "task": spec["task"], "inputs": spec["inputs"],
                    "programs": programs, "domain": name, "model": MODEL,
                    "target_construct": construct,
                    "stratum": "rewrite" if want_rewrite else "ceiling",
                }, sort_keys=True) + "\n")
                sink.flush()
                written += 1

    elapsed = time.time() - started
    print(json.dumps({
        "written_this_run": written, "tasks_total": len(seen),
        "elapsed_s": round(elapsed, 1), "ledger": ledger,
        "stopped_because": ("calls" if ledger.get("calls", 0) >= args.max_calls else
                            "tokens" if ledger.get("output_tokens", 0) >= args.max_output_tokens
                            else "time" if elapsed >= args.max_minutes * 60 else "provider"),
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
